// Fictional, bounded examples for the world_panel contract in contracts/PANELS.json.
const definitions = [
  [
    "person",
    "Person",
    "people",
    "The useful context behind a familiar face.",
    {
      title: "Alex Morgan",
      eyebrow: "Person",
      meta: "Founder · Northstar",
      items: [
        { label: "Last conversation", value: "Onboarding research" },
        { label: "Next step", value: "Share the prototype" },
      ],
    },
  ],
  [
    "commitment",
    "Commitment",
    "remember",
    "A promise with a clear next step.",
    {
      title: "Send the prototype",
      eyebrow: "Commitment",
      body: "You offered Alex an early look at the new onboarding.",
      meta: "Tomorrow · before noon",
      actions: [{ id: "review", label: "Review commitment" }],
    },
  ],
  [
    "decision",
    "Decision",
    "remember",
    "A choice and the reason behind it.",
    {
      title: "Start with one flow",
      eyebrow: "Decision",
      body: "Test account setup before expanding the onboarding study.",
      meta: "Product conversation · just now",
    },
  ],
  [
    "feedback",
    "Feedback",
    "remember",
    "Keep the observation close to its source.",
    {
      title: "The first step feels unclear",
      eyebrow: "Feedback",
      body: "“I wasn’t sure which workspace I was joining.”",
      meta: "Alex · onboarding walkthrough",
    },
  ],
  [
    "insight",
    "Insight",
    "remember",
    "A small connection worth noticing.",
    {
      title: "The same moment of hesitation",
      eyebrow: "Insight",
      body: "Three walkthroughs paused at workspace selection.",
      meta: "Pattern across 3 saved observations",
    },
  ],
  [
    "memory",
    "Memory",
    "remember",
    "Bring back a relevant saved moment.",
    {
      title: "Where you left off",
      eyebrow: "Memory",
      body: "Alex wanted a shorter path from invitation to first project.",
      meta: "Saved conversation · Tuesday",
    },
  ],
  [
    "agent",
    "Agent",
    "work",
    "One task, with an honest progress signal.",
    {
      title: "Finding the shared context",
      eyebrow: "Agent · research",
      body: "Reading the notes from your last two conversations.",
      progress: 0.6,
      meta: "2 sources reviewed",
    },
  ],
  [
    "swarm",
    "Agents",
    "work",
    "Several assistants, one compact status view.",
    {
      title: "Three tasks in motion",
      eyebrow: "Agent team",
      items: [
        { label: "Context", value: "Relevant notes found", state: "done" },
        { label: "Product", value: "Comparing observations", state: "running" },
        { label: "Follow-up", value: "Waiting for context", state: "waiting" },
      ],
    },
  ],
  [
    "approval",
    "Approval",
    "work",
    "Ask for a decision before anything happens.",
    {
      title: "Ready for your review",
      eyebrow: "Approval",
      body: "A follow-up for Alex is ready. Nothing has been sent.",
      actions: [
        { id: "review", label: "Review draft" },
        { id: "hold", label: "Hold for now" },
      ],
    },
  ],
  [
    "draft",
    "Draft",
    "work",
    "A short piece of work, ready to inspect.",
    {
      title: "A note for Alex",
      eyebrow: "Draft · unsent",
      body: "Thanks for the walkthrough. Here’s the prototype we discussed, with a simpler workspace selection.",
      meta: "Follow-up assistant",
      actions: [{ id: "review", label: "Review draft" }],
    },
  ],
  [
    "checklist",
    "Checklist",
    "work",
    "A few steps without the project dashboard.",
    {
      title: "Before the walkthrough",
      eyebrow: "Checklist",
      items: [
        { label: "Open the prototype", done: true },
        { label: "Confirm the research question", done: true },
        { label: "Ask permission to take notes", done: false },
      ],
    },
  ],
  [
    "procedure",
    "Procedure",
    "work",
    "The next useful step in a repeatable process.",
    {
      title: "Turn feedback into a follow-up",
      eyebrow: "Procedure",
      items: [
        { label: "01", value: "Capture the observation" },
        { label: "02", value: "Connect related feedback" },
        { label: "03", value: "Prepare a draft for review" },
      ],
      meta: "Reusable workflow · 3 steps",
    },
  ],
  [
    "timer",
    "Timer",
    "orient",
    "A time cue that stays out of the way.",
    {
      title: "A moment to focus",
      eyebrow: "Timer",
      value: "04:32",
      unit: "remaining",
      progress: 0.54,
      meta: "Sample reading · 10-minute session",
    },
  ],
  [
    "metric",
    "Metric",
    "orient",
    "One number with enough context to matter.",
    {
      title: "Time to first project",
      eyebrow: "Metric",
      value: "2.4",
      unit: "min",
      meta: "Median · 12 sample walkthroughs",
    },
  ],
  [
    "compare",
    "Compare",
    "work",
    "Two choices, presented side by side.",
    {
      title: "Choose a starting point",
      eyebrow: "Compare",
      items: [
        { label: "Guided setup", value: "3 steps · more context" },
        { label: "Quick start", value: "1 step · fewer decisions" },
      ],
      meta: "Prototype alternatives",
    },
  ],
  [
    "meeting",
    "Meeting",
    "people",
    "Who, when, and why you are meeting.",
    {
      title: "Onboarding walkthrough",
      eyebrow: "Meeting",
      value: "14:30",
      unit: "today",
      items: [
        { label: "With", value: "Alex Morgan" },
        { label: "Focus", value: "First project experience" },
      ],
      meta: "Sample schedule · 25 minutes",
    },
  ],
  [
    "reminder",
    "Reminder",
    "remember",
    "The right nudge at the right moment.",
    {
      title: "Close the loop with Alex",
      eyebrow: "Reminder",
      body: "Review the prototype notes before your next conversation.",
      meta: "Tomorrow · 09:00",
      actions: [{ id: "acknowledge", label: "Got it" }],
    },
  ],
  [
    "navigation",
    "Navigation",
    "orient",
    "One direction, with a clear destination.",
    {
      title: "Studio 04",
      eyebrow: "Navigation",
      value: "12",
      unit: "m",
      body: "Ahead, then the second door on your right.",
      meta: "Sample direction · level 2",
    },
  ],
  [
    "object",
    "Object",
    "orient",
    "Useful context for something in the room.",
    {
      title: "Field notes",
      eyebrow: "Object",
      body: "The research notebook from your last product walkthrough.",
      meta: "Sample object · on the table",
      items: [{ label: "Related", value: "Onboarding study" }],
    },
  ],
  [
    "bug",
    "Bug",
    "work",
    "An issue, its impact, and a next step.",
    {
      title: "Invite opens the wrong workspace",
      eyebrow: "Issue",
      body: "Returning members land in their previous workspace after accepting an invitation.",
      meta: "Draft issue · needs reproduction",
      actions: [{ id: "inspect", label: "Inspect details" }],
    },
  ],
  [
    "code",
    "Code",
    "work",
    "A focused technical snippet in context.",
    {
      title: "Keep the destination explicit",
      eyebrow: "Code · proposal",
      body: "const workspace = invite.workspaceId;\nawait openWorkspace(workspace);",
      meta: "Illustrative snippet · not applied",
    },
  ],
  [
    "note",
    "Note",
    "remember",
    "A thought without extra structure.",
    {
      title: "Make room for the conversation",
      eyebrow: "Note",
      body: "Show what matters now. Let the rest stay quietly available.",
      meta: "Personal note · just now",
    },
  ],
  [
    "quote",
    "Quote",
    "remember",
    "Preserve a voice, not just a summary.",
    {
      title: "In their own words",
      eyebrow: "Quote",
      body: "I want to get to the work before I have to understand the tool.",
      meta: "Alex · sample walkthrough",
    },
  ],
  [
    "status",
    "Status",
    "orient",
    "A calm confirmation of what is happening.",
    {
      title: "You’re up to date",
      eyebrow: "Status",
      body: "Your notes are saved. The follow-up is waiting for your review.",
      items: [
        { label: "Capture", value: "Paused", state: "waiting" },
        { label: "Draft", value: "Ready to review", state: "done" },
      ],
    },
  ],
];

export const PANEL_CATALOG = definitions.map(
  ([type, label, category, description, content]) => ({
    type,
    label,
    category,
    description,
    sample: {
      op: "show",
      id: `sample-${type}`,
      type,
      ...content,
      position: "center",
      ttl_ms: 60000,
    },
  }),
);
